### ISSUE TITLE
Missing Callback in Getting Started

### ISSUE THREAD

**Issue by Your-God** [linux-man/LoveFrames#10]
I noticed that you are missing the callback love.textinput in Getting Started. Took me a while to figure out why my textinput wasn't working... I'm not sure how git works so I couldn't fix it myself.

**Comment by linux-man** [comment]
Yes. It's not there because it's not mandatory - only if you use text input, but if you look at [(API) Text Input](https://github.com/linux-man/LoveFrames/wiki/(API)-Text-Input) you will find it there.

Getting Started updated with a comment.

**Comment by Your-God** [comment]
I figured it wasn't mandatory. But, (at least to me) there was no obvious note in TextInput or Getting Started that it was something required for the object to work. But thank you for adding it,
