### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CentauriSoldier** [linux-man/LoveFrames#12]
Thanks so much for keeping this code alive, you're a life-saver.

I emailed Kenny (back when he was upkeeping the code) and told him how I had modified loveframes to use a state system and asked him to add that state functionality: he was kind enough to do so. I think the state system is great and provides a wonderful mechanism for keeping ui code compartmentalised; however, it could still use a few features.

One of those being callback functions (on state change) before the old state is unset and another for when the new state is set. That is, if I have two states named **"Menu"** and **"Game"**, each should have an _**OnOpen**_ and _**OnClose**_ callback function. 

An example of it working would be: if I am in the **"Menu**" state and call **loveframes.SetState("Game")**, the **"Menu**" state's _**OnClose**_ callback function will fire followed by the **"Game"** state's _**OnOpen**_ callback function. Of course, if I am in the **"Menu"** state and call **loveframes.SetState("Menu")**, nothing should happen since the state has not changed.

Here's how I modified my utils.lua file although you may have another idea how to implement it that better suits loveframes. I've included only the modified section of this file.

```
local statecallbacks = {};

--[[---------------------------------------------------------
	- func: SetState(name)
	- desc: sets the current state
--]]---------------------------------------------------------
function loveframes.SetState(name)

	if (loveframes.state ~= name) then

		--fire the closing function of the soon-to-be-closed state
		if (type(statecallbacks[loveframes.state]) == "table" and
			type(statecallbacks[loveframes.state].onclose) == "function") then
			--callback must accept the name of the current state and soon-to-be-opened state as args
			statecallbacks[loveframes.state].onclose(loveframes.state, name);
		end

		local oldstate = loveframes.state;
		loveframes.state = name
		loveframes.base.state = name

		--fire the opening function of the newly-opened state
		if (type(statecallbacks[loveframes.state]) == "table" and
			type(statecallbacks[loveframes.state].onopen) == "function") then
			--callback must accept the name of the current state and previous state as args
			statecallbacks[loveframes.state].onopen(name, oldstate);
		end

	end

end

--[[---------------------------------------------------------
	- func: SetStateOnOpenCallback(name, func)
	- desc: sets a state's opening callback function
--]]---------------------------------------------------------
function loveframes.SetStateOnOpenCallback(name, func)

	if (type(name) == "string" and name:gsub("%s", '') ~= '' and
		type(func) == "function") then

		if (not (statecallbacks[name])) then
			statecallbacks[name] = {};
		end

		statecallbacks[name].onopen = func;
	end

end

--[[---------------------------------------------------------
	- func: SetStateOnOpenCallback(name, func)
	- desc: sets a state's closing callback function
--]]---------------------------------------------------------
function loveframes.SetStateOnCloseCallback(name, func)

	if (type(name) == "string" and name:gsub("%s", '') ~= '' and
		type(func) == "function") then

		if (not (statecallbacks[name])) then
			statecallbacks[name] = {};
		end

		statecallbacks[name].onclose = func;
	end

end
```

What do you think?

**Comment by linux-man** [comment]
> Thanks so much for keeping this code alive, you're a life-saver.

"One is glad to be of service"
> I emailed Kenny (back when he was upkeeping the code)

That was a really long time ago! So you are the State System creator. That's good to know.
Loveframes is a beast, and I avoid to make big dangerous changes - after all, I didn't write the code and I don't know it that well.
Having said that, some changes are welcome, and this one looks harmless.
I'll try your code, but you can create a pull request if you like.

**Comment by CentauriSoldier** [comment]
Okay, I've put in a pull request. I've got some objects I want to add in the future too but they're aways out still. Thanks for checking this out.

**Comment by linux-man** [comment]
Done. Thank you. Later I'll update the wiki, and add some demonstration to the demo.
