### ISSUE TITLE
Text Input unresponsive to non text keys

### ISSUE THREAD

**Issue by marcocultrera** [linux-man/LoveFrames#14]
I was surprised to see that when typing in a text input, there was no response when pressing non text keys, like backspace or delete.

I added to the function newobject:keyreleased(key) the following code and it works properly now:

if (key == "backspace") or (key == "delete") or (key == "left") or (key == "right") or (key == "up") or (key == "down") or (key == "return") or (key == "kpenter") or (key == "tab") then
		self:RunKey(key, false)
	end

Not sure if there's a better way to do it.

**Comment by linux-man** [comment]
I'm also surprised because it works. Did you try the demo application without your modifications?

**Comment by marcocultrera** [comment]
No, I actually didn't... It is possible that I'm running an old version of the library also. Just figured I mentioned it, but I'm glad to see that it works for you.
