### ISSUE TITLE
Love 12.0 changes stencil workflow.

### ISSUE THREAD

**Issue by JoaquinIglesiasTurina** [linux-man/LoveFrames#19]
As documented on [this issue](https://github.com/love2d/love/issues/1818) Love2d 12.0 will introduce changes to the stencil workflow that will break LoveFrames.

As I am on 12.0 now. I will be investigating these issues. 

Could we consider a 12.0 LoveFrames branch so we can start working on these kinds of issues?

**Comment by linux-man** [comment]
Done. You're welcome.
