### ISSUE TITLE
Colored text doesn't work

### ISSUE THREAD

**Issue by pirogronian** [linux-man/LoveFrames#2]
Colored text (as described in [Formatting Text: Colors](https://github.com/linux-man/LoveFrames/wiki/(API)-Text#colors)) dosen't work. All text remains grey (with default skin).
It could be related to Love 11.0 color format change:

> In versions prior to 11.0, color component values were within the range of 0 to 255 instead of 0 to 1.

However, after replacing of `255` with `1`, result is the same.

**Comment by linux-man** [comment]
First, all the examples with color must be converted to the new format.
I'll look into the colored text example. Might be a bug.

**Comment by linux-man** [comment]
Done.
The example (and SetText function) were wrong.
One other thing I did was to create standalone runnable code for almost all the examples as you can already find on (API) Text.
Before, all examples were pasted from LoveFrames Demo, a great learning resource, but unnecessarily complicated for a newbie.

**Comment by pirogronian** [comment]
Indeed. Following new documentation fixed the problem.
