### ISSUE TITLE
grid:Center() does not work

### ISSUE THREAD

**Issue by yashureg** [linux-man/LoveFrames#21]
for this code
`function love.load()

    local grid = loveframes.Create("grid")
    grid:SetRows(4)
    grid:SetColumns(4)
    grid:SetCellWidth(64)
    grid:SetCellHeight(64)
    grid:SetCellPadding(2)
    grid:SetItemAutoSize(true)
    grid:Center()

    local n = 1
    for i=1,4 do
        for j=1,4 do
            local button = loveframes.Create("button")
            grid:AddItem(button, i, j)
            button:SetText(n)
            n = n + 1
        end
    end
    
end`

result looks like this
[https://i.ibb.co/zrXFy3k/1.png](url)

i think it doesn't work right

**Comment by linux-man** [comment]
Grid was only calculating size on update(dt). Now Center() calls a new function - CalculateSize().
Calling CalculateSize() on every little change is overkill, so you can call it yourself after Grid changes.
