### ISSUE TITLE
Custom skin font doesn't apply to text elements and renders incorrectly

### ISSUE THREAD

**Issue by marshallovski** [linux-man/LoveFrames#22]
I'm using OpenSans, that supports both cyrillic and latin.
Love2d version: 11.5
Loveframes version: from this repo (11.3 i think)

My code:
```lua
-- config.loveframes.font = "OpenSans-Regular.ttf"

    local small_font = love.graphics.newFont(config.loveframes.font, 12)
    local imagebuttonfont = love.graphics.newFont(config.loveframes.font, 15)
    love.graphics.setFont(small_font)


    -- Change fonts on all registered skins
    for _, skin in pairs(loveframes.skins) do
        skin.controls.smallfont = small_font
        skin.controls.imagebuttonfont = imagebuttonfont
    end
```

When ukrainian is used: english text is renders correctly, but some text (that squares near two inputs) is not
![зображення](https://github.com/linux-man/LoveFrames/assets/68496774/ad93a100-27bb-4522-818c-a083bcf38eb0)

When english is used:
![зображення](https://github.com/linux-man/LoveFrames/assets/68496774/3b9b3526-7cce-4f2b-b130-6fd5b07a85ab)

When OpenSans Bold is used:

English: "Username" and "Password" are not bold, why?
![зображення](https://github.com/linux-man/LoveFrames/assets/68496774/7c3aff16-1d4a-43f3-877e-b2a7d29be0c6)

Ukrainian:
![зображення](https://github.com/linux-man/LoveFrames/assets/68496774/248d185f-d870-4cc0-932a-edc91639a5cf)

**Comment by marshallovski** [comment]
Ah, forgot to mention: I'm using OpenSans font from Google Fonts. You can test ukrainian support here:
https://fonts.google.com/specimen/Open+Sans?preview.text=%D0%9D%D1%96%D0%BA%D0%BD%D0%B5%D0%B9%D0%BC,%20%D0%9F%D0%B0%D1%80%D0%BE%D0%BB%D1%8C,%20%D0%9B%D0%BE%D0%B3%D1%96%D0%BD

**Comment by linux-man** [comment]
Wiki: https://github.com/linux-man/LoveFrames/wiki/%28API%29-Text#text-font

**Comment by marshallovski** [comment]
> Wiki: https://github.com/linux-man/LoveFrames/wiki/%28API%29-Text#text-font

Thank you, it works!
