### ISSUE TITLE
Form documentation is missing in the wiki

### ISSUE THREAD

**Issue by alejandro-alzate** [linux-man/LoveFrames#24]
I was trying to use SetFont on the form object to change it's header but didn't worked, i was looking for the (API) Form article and it seems missing.

**Comment by linux-man** [comment]
Are you looking for [API-Frame](https://github.com/linux-man/LoveFrames/wiki/%28API%29-Frame)?

**Comment by alejandro-alzate** [comment]
nope, `loveframes.Create("form")`

**Comment by linux-man** [comment]
https://github.com/linux-man/LoveFrames/wiki/(API)-Form

**Comment by alejandro-alzate** [comment]
Then it was missing?

**Comment by alejandro-alzate** [comment]
`c00dc64e39ee6c42cf8746e4dc1a6e9df37ce2ce`
`Created (API) Form (markdown)`

Never mind please excuse me.
Now is there any way to poke the font of the header?
`SetFont()` seems that was never exposed.

**Comment by linux-man** [comment]
Yes. It was forgotten.
SetFont is implemented only on some Objects - Text, Button, Textinput, Checkbox, Radiobutton and Imagebutton.
The rest uses the font defined by Skin.
To change Skin fonts take a look at https://github.com/linux-man/LoveFrames/wiki/Skins-%28Usage%29

**Comment by alejandro-alzate** [comment]
thanks man.

**Comment by linux-man** [comment]
If you want to change the skin font, you can modify skin.controls.smallfont and skin.controls.imagebuttonfont anytime.

-- Change fonts on active skin

```lua
loveframes.GetActiveSkin().controls.smallfont = love.graphics.newFont( "Arial.ttf", 10)
loveframes.GetActiveSkin().controls.imagebuttonfont = love.graphics.newFont( "Arial.ttf", 15)
```
