### ISSUE TITLE
Draw order of frames not recalculated when multiple frames are assigned to parent panel or frame

### ISSUE THREAD

**Issue by Fabimawn** [linux-man/LoveFrames#25]
Issue in short: when frame/panel has a parent, it will not update draw order by grabbed panel, but it will stay in the order the elements were created.

I'm currently writing a game tracking application with some nice features, but i discovered that when you got a parent frame or panel to create bounds for some movable frames to live in while other GUI elements should be outside these bounds (so I can't change the size and position of the base object for this), the frames inside the parent frame/panel that are parentLocked to the parent for this reason won't update their drawing order when you grab a frame that was instantiated before a newer frame, which means I had to create a new function in "frame.lua" called boundsLocked, so that I didn't have to use a parent frame/panel to bounds lock these frames so they would correctly update the draw order.
![Knipsel](https://github.com/user-attachments/assets/b7185b8f-abf3-4316-9c98-f5a2ea15f56c)

**Comment by linux-man** [comment]
Hello. I'm back! Sorry for the delay...
I get that "children" frames don't move to top when clicked. Right?
Please can you replace frame.lua at objects folder and try it?
[frame.lua.zip](https://github.com/user-attachments/files/16851930/frame.lua.zip)

**Comment by Fabimawn** [comment]
Hi thanks for the reply! I have tried the changes and it indeed seems to work now.
However if I remember correctly, this problem was also present when using panels.

Also I've looked into the elegant way this library draws text shadows, and would it be possible to add this shadow property to all text objects? This would also be very handy for me since as you can see am creating applications in Fruitiger Aero style, since modern UI doesn't do it for me.

Also thank you for creating the (in my opinion) most powerful and expansive GUI lib for Love2D. I am really enjoying it!

**Comment by linux-man** [comment]
Since panels are not draggable, I don't see a big problem.

Adding a shadow property to all objects would be too much work. Instead, why don't you create your skin for that purpose? A good start is to edit `function skin.PrintText(text, x, y)`.

Don't thank me - I'm just the [maintainer](https://github.com/linux-man/LoveFrames/wiki/FAQ).

**Comment by Fabimawn** [comment]
I see, thanks! For the shadows I already did make my own changes to some of the objects, so I'll continue doing that then.
