### ISSUE TITLE
bug in demo

### ISSUE THREAD

**Issue by giovifav** [linux-man/LoveFrames#3]
Error

loveframes/objects/textinput.lua:1096: UTF-8 decoding error: Not enough space

Traceback

[C]: in function 'getWidth'
loveframes/objects/textinput.lua:1096: in function 'GetTextCollisions'
loveframes/objects/textinput.lua:367: in function 'mousepressed'
loveframes/objects/frame.lua:582: in function 'mousepressed'
loveframes/objects/base.lua:115: in function 'mousepressed'
loveframes/init.lua:216: in function 'mousepressed'
main.lua:173: in function <main.lua:172>
[C]: in function 'xpcall'

**Comment by linux-man** [comment]
I'll come back in September. Until now, google the error message. You may find something...

**Comment by linux-man** [comment]
Can't replicate the error with demo. Example at https://github.com/linux-man/LoveFrames/wiki/%28API%29-Text-Input works fine. I would ask you what's your language, but with UTF-8 that shouldn't matter.

Related errors found:
https://love2d.org/forums/viewtopic.php?t=80965
https://love2d.org/forums/viewtopic.php?t=10294
https://love2d.org/forums/viewtopic.php?t=8760

Most of them warn to "Make sure your Lua file is saved with UTF-8 encoding (without BOM.)"

**Comment by linux-man** [comment]
Lack of activity...
Closing.
