### ISSUE TITLE
"Error: libs/loveframes/init.lua:305: attempt to index local 'base' (a nil value)" when I require the library

### ISSUE THREAD

**Issue by mutantant** [linux-man/LoveFrames#6]
Have LuaFrames in a libs directory in the project. Just the luaframes dir, not the full repo.

Required with `loveframes = require "libs.loveframes"`

But when Love2D is processing the require command, it throws the error:

`Error: libs/loveframes/init.lua:305: attempt to index local 'base' (a nil value)` and, of course, stops.

Line 305: `loveframes.base = base:new()`

Using the most recent Love2D available on the site, 11.3, on MacOS 10.15.5.

**Comment by mutantant** [comment]
Update:
It seems to have something with this line, 63, in init.lua: `dir = loveframes.utf8.gsub(loveframes.utf8.gsub(dir, "\\", "/"), "(%a)%.(%a)", "%1/%2")`

This is supposed to change "." to "/" in the directory for the library, I suppose for use later. However, it does not, but leaves the path as this: `libs.loveframes`

However, if I hardcode, like this, `dir = "libs/loveframes"`, suddenly it loads just fine.

Also, if the library is in the root directory, fine as well. The issue is only if loveframes is in a subdir, like "libs" or the like. If the loveframes directory is in the same directory as main.lua of the Love source, and the require is simply "loveframes" rather than trying to use it from a subdir, "libs.loveframes", then it works.

I don't quite know why gsub isn't doing its job.

**Comment by mutantant** [comment]
Finally, using string.gsub instead of the third-party UTF8 gsub works as intended: `dir = string.gsub(string.gsub(dir, "\\", "/"), "(%a)%.(%a)", "%1/%2")` produces: `libs/loveframes` and all runs as it should. I'm guessing the third-party utf8 library used here isn't handling things right for some reason.

As a quick fix, simply change line 63 of init.lua to `dir = string.gsub(string.gsub(dir, "\\", "/"), "(%a)%.(%a)", "%1/%2")` and it seems to work.

**Comment by linux-man** [comment]
Thanks for your analysis. I'll update ASAP, and send the bug to utf8 lib mantainer.

**Comment by mutantant** [comment]
Groovy, thanks. Lovely library, great work!

**Comment by linux-man** [comment]
The parsing error you found was already fixed upstream. Please confirm.

**Comment by mutantant** [comment]
Confirmed, thank you. Apologies for the delayed response, as I was otherwise occupied. I have it in a new project, under a libs directory, and require "libs.loveframes" is working as expected.

Excellent work, great little gui library. Thanks again.

**Comment by linux-man** [comment]
You're welcome.
