### ISSUE TITLE
Parenting Objects to Collapsible Category

### ISSUE THREAD

**Issue by Your-God** [linux-man/LoveFrames#7]
I might just be setting this up wrong but when I try to create a Collapsible Category inside a Collapsible Category it seems to mess it up.

``` lua
local Window = loveframes.Create("frame")
Window:SetName("Workspace")
Window:SetScreenLocked(true)
Window:SetPos(0,0)
Window:SetDockable(true)
Window:SetSize(300,300)

local Root = loveframes.Create("collapsiblecategory",Window)
Root:SetPos(0,30)
Root:SetSize(300,300)
Root:SetText("Root")

local Child = loveframes.Create("collapsiblecategory",Root)
Child:SetPos(0,60)
Child:SetSize(300,300)
Child:SetText("Child")
```

If I open up Root or Move the window around it causes Child to be unparented and fall behind the window.
I tried this with Child being a text object and the problem seemed to persist so I think I might just be doing something wrong...

**Comment by linux-man** [comment]
After "Child" creation, do a `Root:SetObject(Child)`

**Comment by Your-God** [comment]
Haha! Thank you, I knew this was too simple to be a bug in the program. Thank you.
