### ISSUE TITLE
SetParent() not working?

### ISSUE THREAD

**Issue by anaseskyrider** [linux-man/LoveFrames#8]
I can't seem to get objects to parent to other objects. It doesn't give me any errors, but no matter what I do -- call :SetParent() or use it during :Create() -- the printed parent is always "instance of class loveframes_object_base".

**Comment by anaseskyrider** [comment]
It would appear that the issue is caused by line #621 in base.lua. SetParent does not allow you to parent to objects other than frames, panels, and lists. The wiki did not explicitly make this clear at all, stating that you could parent to "other objects".

**Comment by anaseskyrider** [comment]
Upon further investigation, a significant amount of different parts of this library are built to only work with the given objects for parenting. Fixing this myself would require quite a bit of work.

I request this be added to other objects to make things like relative positioning easier.

**Comment by linux-man** [comment]
Nikolai had a reason to select forms, panels and lists as valid parents. After all who wants to parent 2 buttons? There's a lot of problems ahead on that road.
Since loveframes is a big monolithic library (hard to change without breaking things), and I'm at maintenance mode right now, it's very unlikely that your request will be granted. Besides, I don't think it's a good idea - looks more like a can of worms. :anguished:
Can't you use a Panel to achieve the results you want - relative positioning? I guess that's what most users do.
Wiki was updated to warn about this limitation.
Thank you very much for your comments. :+1:

**Comment by anaseskyrider** [comment]
Part of why this is an issue was that I could not figure out how to *hide* the panel and *only* the panel. Even setting the size to (0,0) there was a border. I've since learned how to mess with skins and have created a custom skin that replaces skin.OutlinedRectangle with an empty function.

I don't suppose I could tack on a request to this thread -- instead of opening a new one -- to allow frames like Button to use the advanced formatting features afforded by Text? It would make what I'm currently doing -- hide the box of the button but leave the hover/down/click features of the text -- much easier since I have to find a clean way to adjust the text of the button _without_ having to make a custom skin or copy-paste-then-edit the huge button draw function for every button that might use a different font.

**Comment by linux-man** [comment]
You're trying to make things differently and loveframes is all about standardization, right? Skins, all buttons are born equal, etc. :wink:
 
I think you can create an invisible panel overriding Draw function:
``` lua
local panel = loveframes.Create("panel")
panel.Draw = function() end
```
You can use "text as button" - look at "Image Button" for inspiration. It has the hover feature you want.
You can emulate a link with text property linksenabled.
And you can create a custom object, but doing it means that you must also add it to skin code. Maybe too much work.

**Comment by anaseskyrider** [comment]
> You're trying to make things differently and loveframes is all about standardization, right? Skins, all buttons are born equal, etc. 😉

I've already started using skins. I'm early into my project so the only UI elements I have are on the main menu (no submenus _just_ yet). I believe setting a skin before adding children avoids the recursion that affects all child frames, so, fortunately, I shouldn't have any issues just creating the handful of skins I'll likely need for my project. My main menu buttons even do some neat stuff I've hardcoded into the skins like scaling the text on a click.

> I think you can create an invisible panel overriding Draw function:

This was one solution I eventually found, but I went with just making all of my UI follow a "main menu" skin, and disabling the outlined rectangle in that skin. Panels are size (0,0), so they don't show any foreground.

> You can use "text as button" - look at "Image Button" for inspiration. It has the hover feature you want.

So you're telling me it would've been easier to use the image button -- which comes with text -- and just have no image XDDDD. That's fantastic.

> You can emulate a link with text property linksenabled.

I don't understand this one.

> And you can create a custom object, but doing it means that you must also add it to skin code. Maybe too much work.

I tried this and it was hell in a handbasket even trying to figure that one out.

**Comment by anaseskyrider** [comment]
> ```lua
> local panel = loveframes.Create("panel")
> panel.Draw = function() end
> ```

This method appears to cause child frames to not render.
EDIT: `.draw` is what causes this error. `.Draw` does not. Capitalization matters, folks.

**Comment by linux-man** [comment]
> > You can emulate a link with text property linksenabled.
> 
> I don't understand this one.

Works with Internet links, but you could easily adapt the code (text.lua, line 356).
```lua
	local text1 = loveframes.Create("text")
	text1:SetLinksEnabled(true)
	text1:SetDetectLinks(true)
	text1:SetText("lorem ipsum http://somewhere lorem http://otherplace")
	text1.OnClickLink = function(object, text)
		print(text)
	end
```

**Comment by anaseskyrider** [comment]
So, enabling the link components gives me the hover and down states for skinning as well as the enter/leave and click events I'd need? Then I'd just write the callbacks I need to do stuff like, say, enable another frame when I click the "link" button to go to another page -- just like I'd do for a button.

**Comment by linux-man** [comment]
Not so much. You only get `OnClickLink` to work with. You can choose the colors
```
text1.linkcolor = {0, 1, 0, 1}
text1.linkhovercolor = {1, 0, 0, 1}
```
and that's all.

**Comment by anaseskyrider** [comment]
Then I'm happy with my implementation -- using a skin to hide button backgrounds.
