### ISSUE TITLE
[Suggestion] Add :SetFont() to Buttons

### ISSUE THREAD

**Issue by anaseskyrider** [linux-man/LoveFrames#9]
Add control of the font of the button text. I don't know how to do forking or pull requests, so here's the copy-pastable code, I've already implemented it and it seems to work:

objects\button.lua
```
#20 + self.font = nil
```
```
#200 + --[[---------------------------------------------------------
	- func: SetFont(font)
	- desc: sets the object's font, nil uses the skin's default
--]]---------------------------------------------------------
function newobject:SetFont(font)

	self.font = font
	return self

end

--[[---------------------------------------------------------
	- func: GetFont()
	- desc: gets the object's font
--]]---------------------------------------------------------
function newobject:GetFont()

	return self.font

end
```

skins\Default\skin.lua
```
#175 - local font = skin.controls.smallfont
#175 + local font = object:GetFont() or skin.controls.smallfont
```

skins\Blue\skin.lua 
```
#316 - local font = skin.controls.button_text_font
#316 + local font = object:GetFont() or skin.controls.button_text_font
```

It will use the skin's default if a font is not set. That way you can still skin every button to have a certain font, but otherwise you can override it.

**Comment by anaseskyrider** [comment]
Addendum: This would likely need an implementation for other objects using prominent text.

**Comment by linux-man** [comment]
Great. Just use it. I'll take a look and search for issues.

**Comment by linux-man** [comment]
Actually 4 Objects implement setFont - text, textinput, checkbox and radiobutton.
I guess there's no harm on expanding this feature.

**Comment by linux-man** [comment]
But if you want to globally change the font (and that's how loveframes works best), you can use this properties:
```lua
loveframes.GetActiveSkin().controls.smallfont = love.graphics.newFont( "DroidSans.ttf", 10)
loveframes.GetActiveSkin().controls.imagebuttonfont = love.graphics.newFont( "DroidSans.ttf", 15)
loveframes.GetActiveSkin().directives.text_default_font = love.graphics.newFont( "DroidSans.ttf", 12)
```
smallfont is used by Buttons.

**Comment by linux-man** [comment]
SetFont/GetFont added to Button and Imagebutton. Baby steps...
Nice work.
